In [92]:
import os
import csv
import math
import numpy as np
from matplotlib import pyplot
%matplotlib inline

In [93]:
#data reading
reader = csv.reader(open("train.csv", "r"), delimiter=",")
result = list(reader)
trainData = np.array(result)
#print((trainData))


reader = csv.reader(open("test.csv", "r"), delimiter=",")
result = list(reader)
testData = np.array(result)
#print(len(testData))



In [94]:
train_data_features = np.delete(trainData,4 ,axis = 1)
train_data_output =  trainData[:,4]

test_data_features = np.delete(testData,4 ,axis = 1)
test_data_output =  testData[:,4]

train_data_features = train_data_features.astype(np.float)
test_data_features = test_data_features.astype(np.float)

In [95]:
#euclidian distance
def computeDistance(trainData,testData): 
    D = np.sqrt(np.sum(np.subtract(trainData ,testData)**2))
    return D


In [96]:
computeDistance(train_data_features[0],test_data_features[0])

0.5916079783099616

In [157]:
def createDistanceVector(testData):
    distanceArray = list()
    i = 0
    # create as index,distance
    while (i <len(train_data_features)):
        row = train_data_features[i]
        distanceArray.append([i,computeDistance(row,testData)])
        i = i+1
    return distanceArray
    

In [158]:
distanceArray = createDistanceVector(test_data_features[0])
#print(distanceArray)

In [159]:
def predictLabel(distanceVector,K):
    i = 0
    indexes_labels = list()
    
    distanceVector.sort(key = lambda x: x[1])
    
    while(i< K):
        min_index = distanceVector[i][0]
        indexes_labels.append(train_data_output[min_index])
        i = i+1
    
    return max(set(indexes_labels), key = indexes_labels.count) 
    
#predictLabel(createDistanceVector(test_data_features[0]),5)       

In [160]:
#main function that computes the predicted labels for testData
def predictKNN(testData,K):
    predictedLabel = list()
    for row in testData:
        #append in predictedlabael
        predictedLabel.append(predictLabel(createDistanceVector(row),K))
    return predictedLabel        

In [161]:
predictedLabel = predictKNN(test_data_features,60)
print(predictedLabel)

['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-versicolor']


In [107]:
#confusion matrix
def confusionMatrixIrissetosa(predicted_Y, Actual_Y):
    tp = 0
    tn = 0
    fp = 0
    fn = 0
    #for positive
    for i in range(len(Actual_Y)): 
        if predicted_Y[i] == 'Iris-setosa' and Actual_Y[i]== 'Iris-setosa' :
           tp += 1
        if predicted_Y[i]== 'Iris-setosa' and Actual_Y[i]== 'Iris-versicolor':
           fp += 1
        if predicted_Y[i]== 'Iris-setosa' and Actual_Y[i] == 'Iris-virginica':
           fp += 1
        if predicted_Y[i]== 'Iris-versicolor' and Actual_Y[i] == 'Iris-setosa' :
           fn += 1
          # print('A')
        if predicted_Y[i]=='Iris-versicolor' and Actual_Y[i] =='Iris-versicolor' :
           tn += 1
           #print('B')
        if predicted_Y[i]=='Iris-versicolor' and Actual_Y[i] =='Iris-virginica' :
           tn += 1
           #print('C')
        if predicted_Y[i]=='Iris-virginica' and Actual_Y[i] =='Iris-setosa' :
           fn += 1
        if predicted_Y[i]=='Iris-virginica' and Actual_Y[i] =='Iris-versicolor' :
           tn += 1
        if predicted_Y[i]=='Iris-virginica' and Actual_Y[i] =='Iris-virginica' :
           tn += 1

    return(tp, tn, fp, fn)



def confusionMatrixIrisversicolor(predicted_Y, Actual_Y):
    tp = 0
    tn = 0
    fp = 0
    fn = 0
    for i in range(len(Actual_Y)): 
        if predicted_Y[i] == 'Iris-setosa' and Actual_Y[i]== 'Iris-setosa' :
           tn += 1
        if predicted_Y[i]=='Iris-setosa' and Actual_Y[i]== 'Iris-versicolor':
           fn += 1
        if predicted_Y[i]=='Iris-setosa' and Actual_Y[i] == 'Iris-virginica':
           tn += 1
        if predicted_Y[i]=='Iris-versicolor' and Actual_Y[i] =='Iris-setosa' :
           fp += 1
        if predicted_Y[i]=='Iris-versicolor' and Actual_Y[i] =='Iris-versicolor' :
           tp += 1
        if predicted_Y[i]=='Iris-versicolor' and Actual_Y[i] =='Iris-virginica' :
           fp += 1
        if predicted_Y[i]=='Iris-virginica' and Actual_Y[i] =='Iris-setosa' :
           tn += 1
        if predicted_Y[i]=='Iris-virginica' and Actual_Y[i] =='Iris-versicolor' :
           fn += 1
        if predicted_Y[i]=='Iris-virginica' and Actual_Y[i] =='Iris-virginica' :
           tn += 1

    return(tp, tn, fp, fn)



def confusionMatrixIrisvirginica(predicted_Y, Actual_Y):
    tp = 0
    tn = 0
    fp = 0
    fn = 0
    for i in range(len(Actual_Y)): 
        if predicted_Y[i] == 'Iris-setosa' and Actual_Y[i]== 'Iris-setosa' :
           tn += 1
        if predicted_Y[i]=='Iris-setosa' and Actual_Y[i]== 'Iris-versicolor':
           tn += 1
        if predicted_Y[i]=='Iris-setosa' and Actual_Y[i] == 'Iris-virginica':
           fn += 1
        if predicted_Y[i]== 'Iris-versicolor' and Actual_Y[i] == 'Iris-setosa' :
           tn += 1
        if predicted_Y[i]== 'Iris-versicolor' and Actual_Y[i] == 'Iris-versicolor' :
           tn += 1
        if predicted_Y[i]== 'Iris-versicolor' and Actual_Y[i] == 'Iris-virginica' :
           fn += 1
        if predicted_Y[i]=='Iris-virginica' and Actual_Y[i] =='Iris-setosa' :
           fp += 1
        if predicted_Y[i]=='Iris-virginica' and Actual_Y[i] =='Iris-versicolor' :
           fp += 1
        if predicted_Y[i]=='Iris-virginica' and Actual_Y[i] =='Iris-virginica' :
           tp += 1

    return(tp, tn, fp, fn)



In [108]:
# confusionMatrix & Accuracies
def outputParameters(predictedLabel):
    
    print('Confusion matrix for Iris-setosa')
    tp0, tn0, fp0, fn0 = confusionMatrixIrissetosa(predictedLabel,test_data_output)
    matrix = np.array([[tp0,fp0], [fn0,tn0]])
    print(matrix)
    # confusionMatrix Irisversicolor 
    print('Confusion matrix for Iris-versicolor')
    tp1, tn1, fp1, fn1 = confusionMatrixIrisversicolor(predictedLabel,test_data_output)
    matrix = np.array([[tp1,fp1], [fn1,tn1]])
    print(matrix)
    print('Confusion matrix for Iris-virginica')
    # confusionMatrix Irisvirginica
    tp2, tn2, fp2, fn2 = confusionMatrixIrisvirginica(predictedLabel,test_data_output)
    matrix = np.array([[tp2,fp2], [fn2,tn2]])
    print(matrix)
    
    
    #Acuuracies
    accuracy0 = (tp0+tn0)/(tp0+tn0+fp0+fn0)*100
    accuracy1 = (tp1+tn1)/(tp1+tn1+fp1+fn1)*100
    accuracy2 = (tp2+tn2)/(tp2+tn2+fp2+fn2)*100
    print('Accuracy for Iris-setosa',accuracy0)
    print('Accuracy for Iris-versicolor',accuracy1)
    print('Accuracy for Iris-virginica',accuracy2)
    


In [184]:
#Single accuracy
def computeAccuracy(predicted_Y):
    tp=0
    length = len(predicted_Y)
    
    for i in range (length):
        if predicted_Y[i] == test_data_output[i]:
            tp = tp +1
 
    print ('Combined Accuracy is ' ,(tp/length)*100 )   

**OUTPUT**


In [183]:
#FOR K = 1,3,5
print('for k = 1')
predictedLabel = predictKNN(test_data_features,1)
outputParameters(predictedLabel)
computeAccuracy(predictedLabel)
print('\nfor k = 3')
predictedLabel = predictKNN(test_data_features,3)
outputParameters(predictedLabel)
computeAccuracy(predictedLabel)
print('\nfor k = 5')
predictedLabel = predictKNN(test_data_features,5)
outputParameters(predictedLabel)
computeAccuracy(predictedLabel)

for k = 1
Confusion matrix for Iris-setosa
[[ 5  0]
 [ 0 10]]
Confusion matrix for Iris-versicolor
[[ 5  0]
 [ 0 10]]
Confusion matrix for Iris-virginica
[[ 5  0]
 [ 0 10]]
Accuracy for Iris-setosa 100.0
Accuracy for Iris-versicolor 100.0
Accuracy for Iris-virginica 100.0
Combined Accuray is  100.0

for k = 3
Confusion matrix for Iris-setosa
[[ 5  0]
 [ 0 10]]
Confusion matrix for Iris-versicolor
[[ 5  0]
 [ 0 10]]
Confusion matrix for Iris-virginica
[[ 5  0]
 [ 0 10]]
Accuracy for Iris-setosa 100.0
Accuracy for Iris-versicolor 100.0
Accuracy for Iris-virginica 100.0
Combined Accuray is  100.0

for k = 5
Confusion matrix for Iris-setosa
[[ 5  0]
 [ 0 10]]
Confusion matrix for Iris-versicolor
[[ 5  0]
 [ 0 10]]
Confusion matrix for Iris-virginica
[[ 5  0]
 [ 0 10]]
Accuracy for Iris-setosa 100.0
Accuracy for Iris-versicolor 100.0
Accuracy for Iris-virginica 100.0
Combined Accuray is  100.0
